package-lock.json
packages/example/exercises/01.nested-routing/01-02.problem/README.01.md
packages/example/exercises/01.nested-routing/README.md
packages/workshop-app/app/components/icons.tsx
packages/workshop-app/app/components/in-browser-browser.tsx
packages/workshop-app/app/root.tsx
packages/workshop-app/app/routes/_app+/$exerciseNumber.tsx
packages/workshop-app/app/routes/_app+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/routes/_app+/$exerciseNumber_.$stepNumber.tsx
packages/workshop-app/app/routes/_app+/_layout.tsx
packages/workshop-app/app/routes/index.tsx
packages/workshop-app/app/routes/launch-editor.tsx
packages/workshop-app/app/routes/start.tsx
packages/workshop-app/app/routes/test.tsx
packages/workshop-app/app/styles/app.css
packages/workshop-app/app/styles/browser-tabs.css
packages/workshop-app/app/styles/changed-files.css
packages/workshop-app/package.json
packages/workshop-app/postcss.config.js
packages/workshop-app/tailwind.config.js

First step of making this look great — and there's a lot more coming! :) Just getting my feet wet.

feat(browser): initial style pass

---

package-lock.json
packages/workshop-app/app/routes/index.tsx

New Index Page UI

---

packages/workshop-app/app/routes/_app+/$exerciseNumber_.$stepNumber.$type.tsx

add sub title to instruction page

---

packages/workshop-app/app/routes/_app+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/styles/app.css

fix: add shadow to sticky title, with css only

---

packages/workshop-app/app/components/diff.tsx
packages/workshop-app/app/components/icons.tsx
packages/workshop-app/app/components/in-browser-test-runner.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/routes/admin.tsx

add `scrollbar-thin scrollbar-thumb-gray-300` when overflow is in use

fix(style): add sticky title to exercise start page & use thin scrollbars

---

packages/example/exercises/01.nested-routing/01.problem.outlet/app/root.tsx
packages/example/exercises/02.styling/01.problem.links/app/root.tsx

fix copy paste error from e6845e0

chore: fix example/exercises meta, regresion from e6845e0

---

packages/workshop-app/app/routes/_app+/_exercises+/_layout.tsx

feat: show playground emoji in sidebar menu

---

packages/workshop-app/app/components/diff.tsx

fix: open in app from diff tab

---

packages/workshop-app/server/index.ts

make the console output more readable

chore: decode morgan output

---

packages/workshop-app/app/routes/_app+/_exercises+/_layout.tsx

fix: sidebar emoji is out of sync

---

packages/workshop-app/utils/apps.server.ts

fix: globby patterns on windows, don't delete build folders

---

packages/workshop-app/app/routes/_app+/_layout.tsx
packages/workshop-app/utils/apps.server.ts

regression from 46abcb3a1290bf819725f279e3c646d8916fe1c4

fix: extract exercise number from appName

---

packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/routes/_app+/_layout.tsx

now everything have height 56px (h-14)

fix: inconsistent header height

---

packages/workshop-app/app/utils/diff.server.ts

chore: filter out test files from changed files lists

---

packages/workshop-app/other/build-dir.ts

same as https://github.com/epicweb-dev/epic-stack/pull/142

chore: don't copy 'dev-server' to build

---

packages/workshop-app/package.json

fix: playwright export

---

packages/workshop-app/utils/playwright.server.ts

this will fix most of the test in advanced-react-patterns

fix: leftover require

---

packages/workshop-app/app/components/button.tsx
packages/workshop-app/app/styles/app.css

fix: buttons clipped border on hover

---

packages/workshop-app/app/components/accordion.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/utils/diff.server.ts
packages/workshop-app/app/utils/mdx.tsx

fix: better dark mode hover color

---

packages/workshop-app/app/root.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx

fix: Restore scroll position of instructions on refresh

---

packages/workshop-app/app/utils/mdx.tsx

fix: align CodeFile buttons

---

packages/workshop-app/app/components/diff.tsx
packages/workshop-app/app/root.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/routes/_app+/_layout.tsx

hopefully it will address all issues in #99

fix: narrow screen issues

---

packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx

fix: tabs scrollbar z-index

---

docs/development.md

docs: add some development docs

---

packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/routes/_app+/index.tsx
packages/workshop-app/app/routes/launch-editor.tsx

feat: add an "Edit README" for the other readmes

---

docs/mdx.md
packages/example/exercises/01.nested-routing/01.problem.outlet/README.mdx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/types/dom.d.ts

closes #109 
check new section on `docs/mdx.md`

feat: MDX Component: <DiffLink />

---

packages/workshop-app/app/routes/diff.tsx

fix: scrolling on /diff view

---

package-lock.json
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.finished.tsx
packages/workshop-app/app/routes/_app+/finished.tsx
packages/workshop-app/app/routes/_app+/index.tsx
packages/workshop-app/app/utils/mdx.tsx
packages/workshop-app/app/utils/misc.tsx
packages/workshop-app/package.json

This automatically adds IDs and links to heading elements rendered by the `<Mdx />` component.
https://github.com/epicweb-dev/kcdshop/assets/7356098/66b39dda-5ccb-45b9-88ae-6bea7e50bd03

feat: add links to MDX heading elements

---

packages/workshop-app/app/components/icons.tsx
packages/workshop-app/app/root.tsx
packages/workshop-app/app/routes/_app+/_layout.tsx
packages/workshop-app/app/routes/_app+/account.tsx
packages/workshop-app/app/routes/_app+/login.tsx
packages/workshop-app/public/icons.svg

style: auth flow

---

packages/workshop-app/app/components/epic-video.tsx
packages/workshop-app/app/routes/_app+/index.tsx

I thought a list view would be easier to comprehend as well as create space for displaying section level progress.

style: section list

---

packages/workshop-app/app/utils/diff.server.ts

Hi Kent,
I've just looked at your code and I think this is a cleaner approach than my first pull request to tackle the path problem on Windows I mentioned on Discord.
jokele

Fix an issue with the file path on Windows systems

---

packages/workshop-app/utils/git.server.ts

The RegEx didn't match so I've updated it to one that works. Might not be the most elegant RegEx but it seems to work!
fixes #165

fix: diff url username and repo undefined

---

packages/workshop-app/app/routes/admin+/_layout.tsx
packages/workshop-app/app/utils/epic-api.ts

fix: switch to resources on api

---

packages/workshop-app/app/utils/diff.server.ts
packages/workshop-utils/src/apps.server.ts

fix(diff): fix normalization of quoted paths on Windows (closes #236)

---

packages/workshop-app/app/components/exercise-warning-banner.tsx
packages/workshop-app/app/root.tsx
packages/workshop-app/app/routes/_app+/preferences.tsx
packages/workshop-app/app/routes/_app+/workspace-structure.tsx
packages/workshop-utils/src/db.server.ts
packages/workshop-utils/src/git.server.ts

Add a warning system to guide workshop participants to work in the `playground` directory instead of `exercises`.

Add warning and explanation page

---

packages/workshop-utils/src/diff.server.ts

fix(diff): path.normalize issue on windows (closes #270)

---

packages/update-epic-workshop/bin.js
packages/workshop-utils/src/git.server.ts

Add cleanup for empty exercise directories to `updateLocalRepo` to maintain a tidy repository.

Remove empty exercise directories

---

packages/workshop-utils/src/apps.server.ts

Ignore empty directories (excluding gitignored files) when counting exercises and exercise steps.

Ignore empty directories in exercises

---

packages/workshop-app/app/utils/mdx.tsx

Improve copy button reliability by adding error handling and correcting state update logic.

Fix clipboard copy unhandled rejections and UI state
