packages/workshop-app/app/utils/diff.server.ts

The problem caused by `parseGitDiff`
it return mixed separators from `const parsed = parseGitDiff(diffOutput)`
`Users\\____\\AppData\\Local\\Temp\\kcdshop\\diff\\advanced-react-patterns\\exercises.01.latest-ref.01.solution-1/index.tsx"`
it also start/end with `'` or `"`
The proposed patch fix the problem by updating the function `diffPathToRelative`
i've tested it only on windows 11, and the diff work ok

fix diffPathToRelative

---

packages/workshop-app/start.js

Last week when we discussed `process.env.KCDSHOP_EDITOR` I did not created a `.env` file, instead I've just add it as a `windows environment variable`.
Today I've noticed that the app not loading the `.env` file at all.
On kcdshop development
```
[dotenv@16.0.3][DEBUG] Failed to load C:\projects\kcd-apps\kcdshop\packages\example EISDIR: illegal operation on a directory, read
```
On web-app-fundamentals
```
[dotenv@16.0.3][DEBUG] Failed to load C:\projects\kcd-apps\web-app-fundamentals EISDIR: illegal operation on a directory, read
```
Simple fix….

fix: failed to load .env

---

packages/example/exercises/01.nested-routing/01-02.problem/app/root.tsx
packages/example/exercises/01.nested-routing/01-02.problem/remix.config.js
packages/example/exercises/01.nested-routing/01.solution.outlet/app/root.tsx
packages/example/exercises/01.nested-routing/01.solution.outlet/remix.config.js
packages/example/exercises/01.nested-routing/02.solution.outlet-context/app/root.tsx
packages/example/exercises/01.nested-routing/02.solution.outlet-context/remix.config.js
packages/example/exercises/02.styling/01-02.problem/app/root.tsx
packages/example/exercises/02.styling/01-02.problem/remix.config.js
packages/example/exercises/02.styling/01.solution.links/app/root.tsx
packages/example/exercises/02.styling/01.solution.links/remix.config.js
packages/example/exercises/02.styling/02.solution.css-modules/app/root.tsx
packages/example/exercises/02.styling/02.solution.css-modules/remix.config.js
packages/example/exercises/02.styling/03.problem.tailwind/app/root.tsx
packages/example/exercises/02.styling/03.problem.tailwind/remix.config.js
packages/example/exercises/02.styling/03.solution.tailwind/app/root.tsx
packages/example/exercises/02.styling/03.solution.tailwind/remix.config.js
packages/workshop-app/app/root.tsx

According to the docs, It is recommended to use normal `<meta>` tags inside of the root route for `viewport` and `charSet`.
All other routes use only title and we do not have any conflict.
There is no need to use merge Meta function.

chore: update to meta v2

---

packages/workshop-app/tailwind.config.js

I've used `unset` to reset the margin to its default
let me know if you want a different size and if you like to change other typography defaults

fix: remove prose margin from list item first/last child

---

packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/utils/diff.server.ts
packages/workshop-app/utils/cache.server.ts

add cache to `getDiffFiles` calls.
relevant files are always the same for a step.
fix this:

fix: add cache getDiffFiles, use --ignore-blank-lines

---

packages/workshop-app/app/routes/launch-editor.tsx

console warning:
```
REMIX FUTURE CHANGE: `fetcher.type` will be removed in v2. Please use `fetcher.state`, `fetcher.formData`, and `fetcher.data` to achieve the same UX.For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#usefetcher
l
```
[Remix docs example](https://remix.run/docs/en/1.15.0/pages/v2#usefetcher)
```js
// fetcher.type === "done"
let isDone =
fetcher.state === "idle" && fetcher.data != null;
```

chore: `fetcher.type` will be removed in v2

---

packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx

resolves #41 
`).then(a => (isProblemApp(a) ? a : null))` and  `).then(a => (isSolutionApp(a) ? a : null))` are redundant here since `getExerciseApp` already filter for the type

chore: minore cleanup $exerciseNumber_.$stepNumber.$type

---

packages/workshop-app/utils/apps.server.ts
packages/workshop-app/utils/change-tracker.ts

this is all we need to do to solve #46
should it be a `chore` or a `fix` ?

chore: skip cache update when changing playground

---

packages/workshop-app/utils/apps.server.ts

would you consider to enable `eslint` rules for no-shadow and such.

chore: clear repeated calls to getWorkshopRoot

---

packages/workshop-app/app/utils/diff.server.ts

`parseGitDiff` paths in windows are wrapped in double quote, so `path.extname(filepath).slice(1)` return `tsx"` instead of `tsx`
The extra double quote at the end made getLanguage fail to find the correct language.

fix: getLanguage always return 'text' on Windows

---

packages/workshop-app/package.json

`change-tracker` is used by `testing-web-apps` during setup

fix: add missing export

---

packages/workshop-app/app/routes/set-playground.tsx
packages/workshop-app/utils/process-manager.server.ts

while testing remix v1.17 on `testing-web-apps` workshop.
I tripped by this issue when trying to 'Set To PLAYGROUND' while app from other exercise was already running.
```
EPERM: operation not permitted, copyfile
'C:\projects\kcd-apps\testing-web-apps\exercises\02.http-mocking\01.problem.setup\app\routes\resources+\create-host.tsx' --> C:\projects\kcd-apps\testing-web-apps\playground\app\routes\resources+\create-host.tsx'
```
I propose to fix this issue with this patch cf0754d3cfb89b291a8942a9193c7bf39caea644
**noticed** that the app in the iframe flashes for split second, in the time it take to close the current app and kill the port before `setPlayground` can start copy the current app to the playground

fix: Set to Playground fails - EPERM: operation not permitted, copyfile

---

packages/workshop-app/app/components/toast.tsx
packages/workshop-app/public/icons.svg

fix regression from 23274272e6872f4af3d2e28e7c20badaf7980e60
```diff
<symbol
-      id="Error" viewBox="0 0 16 16">
+      id="Error" viewBox="0 0 24 24">
<g fill="none" strokeWidth="2" stroke="currentColor">
<path
strokeLinecap="round"
```
```diff
<symbol
-      id="Notify" viewBox="0 0 16 16">
+      id="Notify" viewBox="0 0 24 24">
<g fill="none" strokeWidth="2" stroke="currentColor">
<path
strokeLinecap="round"
```
```diff
<symbol
-      id="Success" viewBox="0 0 16 16">
+      id="Success" viewBox="0 0 24 24">
<g fill="none" strokeWidth="2" stroke="currentColor">
<path
strokeLinecap="round"
```

fix: wrong toast icons viewBox

---

packages/workshop-app/app/styles/app.css

fix highlight padding and left border on code block without line numbers
left border work for all browsers
`padding 0` work only for browsers that support css .has() which is 87.43% as of today

fix: update prose line highlight padding and left border

---

packages/workshop-app/utils/codefile-mdx.server.ts

closes #101 
I have added new `stripIndent` function instead of importing it.
You may see `CodeFile Warning` for code fence that changed by the new function. 
maybe you can add clear cache to `npm run setup` on each workshop?

fix: make CodeFile de-indent its contents

---

packages/workshop-app/app/utils/mdx.tsx

fix: use thin scrollbar for mdx pre tag

---

packages/workshop-app/app/components/diff.tsx
packages/workshop-app/app/root.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx
packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.finished.tsx
packages/workshop-app/app/routes/_app+/_layout.tsx
packages/workshop-app/app/routes/_app+/finished.tsx
packages/workshop-app/app/routes/_app+/index.tsx
packages/workshop-app/app/routes/set-playground.tsx

closes #118 
This PR add fixed header on all pages when `ENV.KCDSHOP_DEPLOYED` is true.
I've managed to fix all scroll issues by using `h-screen` only in one place in the body. All other places use `h-full` if needed. The main exercises layout has been changed to a two-column grid with one row on large screens and one column with two rows on narrow screens. This change solves all scroll issues on diff views.”

feat: add notice on deployed version

---

packages/workshop-app/app/styles/app.css

fix: set default colors for markdown code fence without language

---

packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.finished.tsx
packages/workshop-app/app/routes/_app+/finished.tsx

Google Forms automatically detects the language of the user’s browser and displays the form in that language, if it is supported. This includes displaying the form in a right-to-left (RTL) layout for languages that are written from right to left, such as Arabic and Hebrew.
since you form is in English, it should always renders left-to-right
this PR fix this issue by appending `&hl=en` to the form’s URL

fix: always render google form LTR

---

packages/workshop-app/app/components/touched-files.tsx
packages/workshop-app/app/routes/launch-editor.tsx
packages/workshop-app/app/utils/diff.server.ts
packages/workshop-app/app/utils/launch-editor.server.ts

closes #131
this PR handle opening single file from `Relevant Files` dropdown on the line near the first diff in the file.
if you want to do the same for `Open All Files` we will have to modify `launchEditor` to spawn separate child process for each file.
I did not managed to launch multiple file in specific line from single command from windows terminal.
I am not sure that this is safe to do without testing

feat: open relevant file on first diff line

---

packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber_.$stepNumber.$type.tsx

@kentcdodds , your previous approach can trigger 'Save As' dialog in some browsers / operating system, when clicking a link when Alt is down.
Using useState to check for alt can be tricky since it is not a synchronous function. React click handler can run before useState update altDown value.
this PR improve the use of Alt to navigate to full-page diff view.
follow-up to 9bc0245a6d8785474b80c5b8afdb34796d0a2123
with the code in this PR we only check if Alt is down when the link clicked, only if the Alt is down we navigate to `full-page diff`

fix: better easy full-page diff view access

---

packages/workshop-app/app/utils/diff.server.ts

@kentcdodds 
I really hate these weired Windows paths. I've installed the new package, but because "path.normalize" changes "/" to "\\" on Windows systems, the check of "b/" and "a/" doesn't work anymore.
Because I don't know, if you use "a/" and "b/" on Unix systems as well, I extended the check, so all four options are checked now.
if (normalizedPath.startsWith('a\\\\') || normalizedPath.startsWith('b\\\\') || normalizedPath.startsWith('a/') || normalizedPath.startsWith('b/')) {...}

Still an issue with the Windows path

---

packages/workshop-app/app/routes/_app+/_exercises+/$exerciseNumber.tsx
packages/workshop-app/app/routes/_app+/index.tsx

Avoids this happening on large screens:
Instead, the font size stops growing if `6vw` reaches `8.5rem` (which is still BIG and keeps the same overall design vibe of big headline).
Same on smaller screens, text size will be clamped to a minimum of `3rem`.
CSS `clamp()` is broadly supported across browsers:

Clamp the main page heading size to avoid overblow

---

packages/workshop-presence/package.json
packages/workshop-utils/package.json

Can be removed again once https://github.com/nrwl/nx/pull/21719 is released
The config is only needed in cases where a project only has a package.json (and no project.json). The workshop-app project has a project.json so doesn't need the additional config.
Verified all three projects are correct:

chore: restore project level config for now

---

docs/other.md

- Elaborates on what the placeholder values actually do and that you have to keep them.
- Explains the intention behind the placeholder values.
- Adds exact instructions hot to get the pre-filled link. Even if these get out of date, I kept the original link to Google docs, which can also get out of date.

improve the custom feedback forms docs

---

project.json

This should make it so that `@kentcdodds/workshop-app:build` is run before `kcdshop:build` and you don't get this error any more:
```
[Error: [remix] ENOENT: no such file or directory, open '/home/runner/work/kcdshop/kcdshop/packages/workshop-app/build/client/.vite/manifest.json']
```

chore(build): kcdshop depends on workshop-app

---

docs/development.md

While contributing to the repo, I found the development instructions not working for me. Specifically, the `EPICSHOP_CONTEXT_CWD` env variable was not picked up by `npm run dev` if set separately in the path (current terminal).
Instead, what worked was to set that variable as a part of the `npm run dev` command itself. 
I've updated the `development.mdx` document to have the instructions that worked for me on MacOS. I've also structured other OS examples with headings to they are easier to find visually. Let me know if this makes sense to you.

docs: improve "development" docs

---

packages/workshop-app/app/utils/diff.server.ts

- Fixes #212
I've fixed that styles of that Markdown snippet to this:
- Added the same consistent padding;
- Marked the text as muted to highlight it's not something to pay attention to;
- Added bottom border to visually separate the standalone string from the following `<details>` of the next file in the diff.

fix: style the "No changes" label in the Diff panel

---

packages/update-epic-workshop/bin.js
packages/workshop-utils/src/git.server.ts

Otherwise, following git stash pop command would fail.
The change is to use --include-untracked flag in the stash command.
Fixes https://github.com/epicweb-dev/epicshop/issues/224

 Include untracked files when stashing before repo update

---

packages/workshop-app/app/styles/app.css

Fixes https://github.com/epicweb-dev/react-fundamentals/issues/397
In exercises/07.forms/04.solution.submit/submit.test.ts (and most of the 07 lessons) we programmaticly click [submit] on the form, but in Firefox most events are blocked inside hidden iframes (submit(), click() etc.) due to a 23-year-old bug.
Instead of hiding the divs containing the iframes, this css fix simply resizes the test accordians to `height:0`.
Tests fine in Chrome, Brave, Safari and Firefox.

fix(firefox): Mocklogs[0] is undefined

---

packages/workshop-cli/package.json
packages/workshop-cli/src/cli.ts

Remove direct workshop app dependency from CLI and enhance app location discovery.
The CLI no longer directly depends on the workshop app, making it lighter. The app's location is now determined dynamically at runtime via a prioritized list: environment variable, CLI flag, Node.js resolution, or global installation. This PR also modernizes internal file system and process operations to use async/await with promise-based APIs and `node:` prefixed imports.

Update workshop CLI dependency handling

---

packages/workshop-utils/src/config.server.ts

Configure StackBlitz to show only the editor and a default file for simple exercises without a package.json.

Configure stackblitz editor display

---

packages/workshop-app/app/routes/video-player/index.tsx

Fix `AbortError` on video play by adding `metadataLoaded` check and removing redundant error handling.

Fix video playback bug in key press

---

packages/workshop-app/app/routes/_app+/exercise+/$exerciseNumber_.$stepNumber.$type+/_layout.tsx
packages/workshop-app/app/routes/launch-editor.tsx
packages/workshop-cli/src/cli.ts
packages/workshop-utils/src/git.server.ts

Fix GitHub file link formatting for deployed environments.
Previously, links included line/column information as `,line,column` (e.g., `index.tsx,4,1`) instead of the correct `#Lline` format (e.g., `index.tsx#L4`), because the `appFile` parameter was not parsed correctly. This PR now parses `appFile` to extract the filename and line number, and formats the URL correctly. It also ensures `tree` is converted to `blob` for individual file links.

Fix GitHub link formatting

---

packages/workshop-utils/src/compile-mdx.server.ts
packages/workshop-utils/src/compile-mdx.test.ts

- Fix issue where titles containing backticks were truncated
- Update title extraction to handle all child nodes in heading
- Preserve inline code formatting (backticks) in titles
- Strip other formatting like bold/italic to clean text
- Add comprehensive tests for title extraction scenarios
Resolves #349

fix: properly extract titles with backticks in MDX headings
